experiment:
  name: cvae_invariant
  seed: 42
  output_dir: experiments/results

data:
  domains: ["DRIAMS_A", "DRIAMS_D"]
  normalization: row_minmax
  test_size: 0.2
  batch_size: 64
  use_species_weights: False

model:
  type: cvae_invariant
  latent_dim: 64
  cond_dim: 2

training:
  epochs: 200
  annealing_epochs: 100
  patience: 40
  metrics_plot_title: "cVAE Invariant"

evaluation:
  use_domain: false
  compute_tsne: true
