experiment:
  name: vae_multidecoder_prior_multiamr
  seed: 42
  output_dir: /export/usuarios_ml4ds/agnavarr/MALDIAlign/experiments/results

data:
  pkl_path: /export/usuarios01/agnavarr/MALDIAlign/amr_global_final_v3.pkl
  domains: ["DRIAMS_A", "DRIAMS_B", "DRIAMS_C", "MARISMA"]
  species_list: ["Escherichia_Coli"]
  antibiotics_filter: ["Ceftazidime"]
  normalization: row_minmax
  test_size: 0.2
  batch_size: 256
  use_species_weights: False

model:
  type: vae_multidecoder_prior_amr_head_zchinos
  latent_dim: 128
  num_domains: 4
  n_species: 1
  n_antibiotics: 1

training:
  epochs: 200
  lr: 1e-4
  lambda_amr: 100
  patience: 30
  metrics_plot_title: "VAE Multidecoder w/prior for species + AMR"

evaluation:
  use_domain: false
  compute_tsne: false
