experiment:
  name: vae_multidecoder_prior_amr_embeddings
  seed: 42
  output_dir: experiments/results

data:
  pkl_path: /export/usuarios01/agnavarr/MALDIAlign/experiments/amr/pickles/K-CEF.pkl
  domains: ["DRIAMS_A", "DRIAMS_B", "DRIAMS_C", "DRIAMS_D"]
  normalization: row_minmax
  test_size: 0.2
  batch_size: 256
  use_species_weights: False

model:
  type: vae_multidecoder_prior_amr_embeddings
  latent_dim: 128
  num_domains: 4
  n_species: 1
  n_antibiotics: 1

training:
  epochs: 200
  lr: 1e-4
  lambda_amr: 75
  annealing_epochs: 50
  patience: 20
  metrics_plot_title: "VAE Multidecoder w/prior for species + AMR"

evaluation:
  use_domain: false
  compute_tsne: true
