experiment:
  name: finetuning_vae_multidecoder_prior
  seed: 42
  output_dir: experiments/results

data:
  domains: ["DRIAMS_A", "DRIAMS_B", "DRIAMS_C", "MARISMA", "RKI"]
  normalization: row_minmax
  test_size: 0.2
  batch_size: 64
  use_species_weights: False

model:
  type: vae_multidecoder_prior
  latent_dim: 64
  num_domains: 5
  n_species: 6

training:
  epochs: 200
  lr: 1e-4
  annealing_epochs: 100
  patience: 40
  metrics_plot_title: "VAE Multidecoder w/prior for species"

evaluation:
  use_domain: false
  compute_tsne: true
