experiment:
  name: vae_bernoulli
  seed: 42
  output_dir: experiments/results

data:
  domains: ["DRIAMS_A", "DRIAMS_B", "DRIAMS_C", "MARISMA", "RKI"]
  species_list: ["Klebsiella_Pneumoniae","Escherichia_Coli","Staphylococcus_Aureus","Pseudomonas_Aeruginosa","Enterococcus_Faecium", "Enterobacter_cloacae_complex"]
  normalization: row_minmax
  test_size: 0.2
  batch_size: 128
  use_species_weights: False

model: 
  type: vae_bernoulli
  latent_dim: 64
  num_domains: 1
  use_specie_prior: False

training: 
  epochs: 100
  lr: 1e-4
  annealing_epochs: 100
  patience: 20
  metrics_plot_title: "VAE"

evaluation:
  compute_tsne: False
  use_domain: False