experiment:
  name: dann
  seed: 42
  output_dir: experiments/results

data:
  domains: ["DRIAMS_A", "DRIAMS_D"]
  normalization: row_minmax
  test_size: 0.2
  batch_size: 64
  use_species_weights: False

model: 
  type: dann
  latent_dim: 64
  source_domain_id: 0   # DRIAMS_A
  n_species: 6
  num_domains: 2
  lambda_domain: 0.01
  
training: 
  epochs: 200
  lr: 1e-4
  annealing_epochs: 100
  patience: 40
  metrics_plot_title: "DANN"

evaluation:
  compute_tsne: True
  use_domain: False
