experiment:
  name: vae_multidecoder
  seed: 42
  output_dir: experiments/results

data:
  domains: ["DRIAMS_A", "DRIAMS_D"]
  normalization: row_minmax
  test_size: 0.2
  batch_size: 64
  use_species_weights: False

model:
  type: vae_multidecoder
  latent_dim: 64
  num_domains: 2

training:
  epochs: 300
  lr: 1e-4
  annealing_epochs: 150
  patience: 60
  metrics_plot_title: "VAE Multidecoder"

evaluation:
  use_domain: false
  compute_tsne: true
